### ISSUE TITLE
Crashes on playlists spotify has imported (i.e. local/iTunes playlists)

### ISSUE THREAD

**Issue by ZacSweers** [mauimauer/portify#3]

**Comment by mauimauer** [comment]
That could very well be the case. I have never tested portify with playlists containing "local" tracks. I'll check what I can do.

**Comment by markimark** [comment]
Yes, this is definately the case. I did some test with our playlists after the app was crashing all the time after I successfully transfered 2 lists before. It turned out that the app can only work with native Spotify playlists. So what I did to fix it, was to create a new playlist in Spotify, copied all songs from the imported list in there and the app was ready to beam it to google music.

Maybe this is something you want a closer look at it. BTW, it is such a great app that you created. I appreciate every loine of code you wrote for all of us. It is such a shame that this is not a default feature of google music. sometimes I really don't understand what kind of people do those jobs there.
