### ISSUE TITLE
Violating TOS

### ISSUE THREAD

**Issue by craftbyte** [mauimauer/portify#92]
May I ask if this does really violate the TOS, since I don't know if @mauimauer read the TOS. If someone did, can they quote the part that is violated?

**Comment by mauimauer** [comment]
One example:

https://play.google.com/intl/en/about/play-terms.html
6. [...] Following payment of the applicable fees for a Product, you will have the non-exclusive right, for the period selected by you in the case of a purchase for a rental period, and in other cases for as long as Google and the applicable copyright holder have rights to provide you that Product, to download or stream, in each case, **solely as expressly permitted by Google via the Play user interface**" [...]

Is probably enough. Also notice that since portify accesses both service using undocumented interfaces (not public APIs). So in theory both services do not really need a reason to terminate your account if they would want to.

**Comment by craftbyte** [comment]
I was referencing to the hosting, since that could bring NodeGear some problems .
-- 
Anže Jenšterle

**Comment by craftbyte** [comment]
also, that only means you will not pirate music

**Comment by mauimauer** [comment]
Still, the one running the instance provides means to access both services in a way expressly not made available by Spotify or Google. If they would, there would be a documented API along with a separate TOS governing the API access. But hey, you can still do what you want, I'm just handing out advice here. IANAL
